### ISSUE TITLE
Executing command for operation ["create"] failed. System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#270] opened 2019-11-18 19:50 UTC
During startup of the docker images the next errors are many times in the log (below).
The adb shell command used is: docker logs edgeAgent .  It is in firmware version 4.8 v0.4940_Perf, v0.5280_Perf and edgeAgent 1.0 to 1.0.8.3

I do not like error logs as they might indicate something is not working. Maybe something is wrong or should this go to Iot Hub forum?

===
<6> 2019-11-18 19:40:51.818 +00:00 [INF] - Executing command: "Create module AIVisionDevKitGetStartedModule"
<3> 2019-11-18 19:43:03.524 +00:00 [ERR] - Executing command for operation ["create"] failed.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpBufferedStream.ReadLineAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs:line 62
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.SetResponseStatusLine(HttpResponseMessage httpResponse, HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 131
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.DeserializeResponse(HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 65
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 36
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.GeneratedCode.EdgeletHttpClient.CreateModuleAsync(String api_version, ModuleSpec module, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/generatedCode/EdgeletHttpClient.cs:line 174
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation)

**Comment by jkubicka** [comment] 2019-11-18 21:44
@V4A001 Please try running this command to download the image before starting the Edge Agent and see if it clears up the error logs:

sudo docker pull mcr.microsoft.com/aivision/visionsamplemodule:1.1.3-arm32v7

**Comment by V4A001** [comment] 2019-11-18 23:59
For some reason I lose connectivity all the time.
https://github.com/microsoft/vision-ai-developer-kit/issues/267

**Comment by V4A001** [comment] 2019-11-21 00:04
Connectivity is being resolved in this thread.

I guess this issue might be resolved with this commit on [https://github.com/Azure/iotedge](https://github.com/Azure/iotedge/commit/d2115b6d017c28dec66ca3b43b2f7712f6278766)

**Comment by jkubicka** [comment] 2019-11-21 17:24
Closing as duplicate of #267

**Closed by jkubicka** 2019-11-21 17:24 UTC
Labels: SupportNeeded

**Comment by V4A001** [comment] 2019-11-21 23:10
Once the images are present this error does not occur anymore. So rebooting and rebooting with same image does not give issue. Should this go to the edgeIoT form as errors which are not caught properly in a try-exception are not so nice to see and distract.

<6> 2019-11-21 22:37:25.237 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module edgeHub]\n  [Start module edgeHub]\n)"
<6> 2019-11-21 22:37:25.237 +00:00 [INF] - Executing command: "Create module edgeHub"
<6> 2019-11-21 22:37:39.655 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2019-11-21 22:37:41.560 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module WebStreamModule]\n  [Start module WebStreamModule]\n)"
<6> 2019-11-21 22:37:41.560 +00:00 [INF] - Executing command: "Create module WebStreamModule"
<6> 2019-11-21 22:38:37.498 +00:00 [INF] - Executing command: "Start module WebStreamModule"
<6> 2019-11-21 22:38:38.251 +00:00 [INF] - Plan execution ended for deployment 23
<3> 2019-11-21 22:38:38.261 +00:00 [ERR] - Edge agent plan execution failed.
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpBufferedStream.ReadLineAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs:line 62
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.SetResponseStatusLine(HttpResponseMessage httpResponse, HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 131
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.DeserializeResponse(HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 65
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 36
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.GeneratedCode.EdgeletHttpClient.CreateModuleAsync(String api_version, ModuleSpec module, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/generatedCode/EdgeletHttpClient.cs:line 174
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 203
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 96
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
