### ISSUE TITLE
Thoughts on Platform Tools - Documentation 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#285] opened 2020-01-03 01:07 UTC
Regarding the Documentation page:  Platform Tools 
https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/#download-links

Maybe add this to Trouble Shooting ? 

To Install the tools in Linux ( eg: Ubuntu on Windows 10 ): 
# sudo apt install adb
# sudo apt install fastboot  
Note, you might have to run 
	#sudo apt-get update 

However, if running adb in Ubuntu yields: 

$ adb devices
List of devices attached

$ adb reboot
error: no devices/emulators found 

It might be the ubuntu adb version  is the problem.  

$ adb devices
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully

Solution: 

in Ubuntu: 
# sudo apt remove adb
# sudo apt remove fastboot  
Note, you might have to run 
	#sudo apt-get update 
# cd /usr/local/bin
# sudo –i
# curl  -Lkv https://dl.google.com/android/repository/platform-tools-latest-linux.zip --output platform-tools-latest-linux.zip
# unzip platform-tools-latest-linux.zip

Add to your $HOME/.profile file eg: 
    # Add Adb etc for vision kit and iot hub
    PATH=${PATH}:/usr/local/bin/platform-tools 

Logout of root
$ cd $HOME 
$ . .profile

**Comment by PuneetRahejaMS** [comment] 2020-01-03 11:55
Hello @juniem ,  @MikeWilcoxMicrosoft has suggested an update in the documentation. Can you kindly look into this request.

**Comment by MikeWilcoxMicrosoft** [comment] 2020-01-03 18:49
I have consolidated my notes on this topic to https://github.com/microsoft/vision-ai-developer-kit/issues/289#issue-545098566

**Comment by vasantha-Mindtree** [comment] 2020-01-06 10:52
Closing this issue as duplicate of issue #289

**Closed by vasantha-Mindtree** 2020-01-06 10:52 UTC
Labels: FeatureRequest
