### ISSUE TITLE
Reset device experience shows wrong leds

### ISSUE THREAD

**Issue by juniem** [microsoft/vision-ai-developer-kit#234] opened 2019-08-27 22:26 UTC
Repro steps: Set up Vision AI Dev Kit normally. Press the power button for 5 seconds, have device to run AP mode, log to device's WiFi and when prompted the web page select to "reset the device".

Reset feature itself runs normally, but the device led colors don't match the expected colors. I have several repros where device leds blinked amber during the whole OOBE experience. This is really confusing as the device works normally, but the leds make to suspect that something is wrong.

**Comment by jkubicka** [comment] 2019-08-30 18:06
Jussi reported at least 10 devices with incorrect LED's. Would bump this issue into a higher priority.

**Comment by Devinwong** [comment] 2019-09-02 05:30
Checked with Altek.
This is by design.
Blinking oranges = Static green + blinking Red
= It's connected to IoT Hub and the device is ready for setup.
Could we add this row in the LED's table to explain this?

**Comment by TELEMEMORY** [comment] 2019-09-16 18:08
I have a device slowly blinking Red.  Not even amber blinking or red consistent blinking.  This is a new thing.

**Comment by jkubicka** [comment] 2019-09-16 22:20
@TELEMEMORY Find the device ID (MSIoT-XXXXXX) in your Wi-Fi tray and connect for setup.

**Comment by TELEMEMORY** [comment] 2019-09-17 01:05
Jan.

It does not work.  I’ve tried multiple times.  It does not recognize the password I previously set up on the device for wifi connection and I have no idea what is going on.

**Comment by jkubicka** [comment] 2019-09-17 03:52
@TELEMEMORY SSH password or device password? If device password for device setup, try the password on the tag on the bottom of the device.

**Comment by patgarr** [comment] 2019-10-28 20:40
Fix for this was checked into FW v0.5280.

**Closed** 2019-10-28 20:40 UTC
Labels: Bug
