### ISSUE TITLE
Azure IoT Edge Runtime not resolving

### ISSUE THREAD

**Issue by TELEMEMORY** [microsoft/vision-ai-developer-kit#239] opened 2019-09-09 18:47 UTC
The Azure IoT Edge runtime download has not stopped running for multiple hours.  http://setupaicamera.ms/ - i don't know what is happening.  I cannot move to test the camera because I can't get past this screen

![IOT_RUNTIME_ISSUE](https://user-images.githubusercontent.com/51130140/64557966-650c1300-d308-11e9-80e6-f05b22ded99f.png)

**Comment by jkubicka** [comment] 2019-09-09 20:26
Hi @TELEMEMORY What firmware version are you running on the device?

**Comment by TELEMEMORY** [comment] 2019-09-09 21:05
v0.4940_Perf

**Comment by TELEMEMORY** [comment] 2019-09-09 21:05
This is the default firmware that ships with the product

**Comment by jkubicka** [comment] 2019-09-09 21:07
@patgarr any idea why OOBE is stuck on this screen, and how to get past?

**Comment by patgarr** [comment] 2019-09-09 22:46
On that page it is primarily downloading and spinning up the individual container modules so it could either be an issue with network connectivity or the docker configuration.  @TELEMEMORY - can you send some basic logs, we can take a look and see if there is something more specific we can recommend.  If you open a command prompt where you installed the platform tools, you can run the following and send us the resulting log.

echo %date% %time% > Peabodylogs.txt
echo FW Version >> Peabodylogs.txt
adb shell cat /etc/version >> Peabodylogs.txt
echo Ping >> Peabodylogs.txt
adb shell ping -c 2 1.1.1.1 >> Peabodylogs.txt
echo WiFi connectivity >> Peabodylogs.txt
adb shell ifconfig wlan0 >> Peabodylogs.txt
echo Disk space usage >> Peabodylogs.txt
adb shell du -c -h -s >> Peabodylogs.txt
echo DNS settings >> Peabodylogs.txt
adb shell cat /etc/resolv.conf >> Peabodylogs.txt
echo Docker daemon json >> Peabodylogs.txt
adb shell cat /etc/docker/daemon.json >> Peabodylogs.txt
echo.
echo Battery level >> Peabodylogs.txt
adb shell cat /sys/class/power_supply/battery/capacity >> Peabodylogs.txt

echo Docker >> Peabodylogs.txt
adb shell docker ps >> Peabodylogs.txt
adb shell docker ps -a >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- EdgeAgent logs >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb shell docker logs edgeAgent >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- EdgeHub logs >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb shell docker logs edgeHub >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- ADB logcat >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb logcat -d >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- Linux host processes >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb shell ps >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- AIVisionDevKitGetStartedModule logs >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb shell docker logs AIVisionDevKitGetStartedModule >> Peabodylogs.txt

echo ___________________________ >> Peabodylogs.txt
echo ---- WebStreamModule logs >> Peabodylogs.txt
echo ___________________________ >> Peabodylogs.txt
adb shell docker logs WebStreamModule >> Peabodylogs.txt

**Comment by TELEMEMORY** [comment] 2019-09-10 14:44
Sorry - I am not sure how to run these commands.  I am running ADB.exe from the powershell but when I run this code I get errors.

**Comment by jkubicka** [comment] 2019-09-11 18:07
@TELEMEMORY try opening a command prompt as an administrator, then 

cd <platforms tools path>

then try running these log commands.

**Comment by jkubicka** [comment] 2019-09-13 18:05
@TELEMEMORY Here are the instructions on how to install/use platform tools:

https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/

**Comment by bmount** [comment] 2019-09-17 19:43
Following up on the discussion in Gitter, I'll attach the adb logs for "Peabody" described above (which I'm assuming shares some DNA with: https://github.com/sseiber/peabody-local-service ?).

[Peabodylogs.txt](https://github.com/microsoft/vision-ai-developer-kit/files/3623099/Peabodylogs.txt)

(Incidentally, that second, peabody-local-service project seems to run, though there is no camera output visible where the UI makes room for it and I wasn't able to load a model.)

This is only partly responsive to @patgarr's request for logs because I don't think my OOBE installation steps even reached the loading of the containerized agent and services:

```
bash-4.4# ls /data/storage/edge
edgeAgent/ edgeHub/   
bash-4.4# ls /data/storage/edgeAgent/
bash-4.4# ls /data/storage/edgeHub/  
bash-4.4# docker logs edgeAgent
Error: No such container: edgeAgent
bash-4.4# docker logs edgeHub  
Error: No such container: edgeHub
bash-4.4# docker logs AIVisionDevKitGetStartedModule
Error: No such container: AIVisionDevKitGetStartedModule
bash-4.4# docker logs WebStreamModule
Error: No such container: WebStreamModule
```
On the other hand I am able to execute some of the fundamental DSP validation tools from the Qualcomm SNPE:

```
bash-4.4# export ADSP_LIBRARY_PATH=/usr/lib/
bash-4.4# ./arm-oe-linux-gcc8.2hf/snpe-platform-validator --runtime dsp
PF_VALIDATOR: DEBUG: Calling PlatformValidator->setRuntime
PF_VALIDATOR: DEBUG: Calling PlatformValidator->IsRuntimeAvailable
PF_VALIDATOR: DEBUG: CPU side validation passed.

PF_VALIDATOR: DEBUG: starting calculator test
PF_VALIDATOR: DEBUG: Successfully loaded DSP library - 'libcalculator_domains.so'.  Setting up pointers.
PF_VALIDATOR: DEBUG: Success in executing the sum function
Runtime DSP Prerequisites: Present.
```

So it seems likely the OS is appropriately built for vision tasks. (The GPU runtime had some other error but I'm most interested in the Hexagon for now.)

With access to the BSP and/or the installer for components like edgeAgent I could maybe figure out what is going on.

**Comment by jkubicka** [comment] 2019-09-18 19:35
@TELEMEMORY Closing this issue. Please re-open if you're still having this issue.

@bmount Is this a new issue or duplicate of https://github.com/microsoft/vision-ai-developer-kit/issues/243? If new issue, please create a new GitHub ticket.

If this is a duplicate issue of https://github.com/microsoft/vision-ai-developer-kit/issues/243, we'll address in that ticket thread instead.

**Closed by jkubicka** 2019-09-18 19:35 UTC
Labels: SupportNeeded

**Comment by ckcampbell248** [comment] 2019-10-06 18:30
I'd like to reopen this issue. I'm having the same problem. 

I'm trying to reconfigure my camera. I can get it back into AP mode (three blinking orange lights) and connect and run through the OOTB experience. I can connect to Azure and IoT Hub and the device gets created on my IoT Hub. When I get to the "Your camera is downloading IoT Edge Runtime" page, it never finishes and eventually times out. 

During this process, it stays in AP mode. I thought it was supposed to switch to the WiFi network I supplied during setup before the download started?

I ran the log script that you asked the OP for and have attached the output. 

[Peabodylogs.txt](https://github.com/microsoft/vision-ai-developer-kit/files/3694721/Peabodylogs.txt)

Any help you can offer would be appreciated.

**Comment by patgarr** [comment] 2019-10-07 19:55
@ckcampbell248 can you send the following logs?  It sounds like a connectivity issue with Docker but these might help us narrow down where it is failing to download.

adb shell ifconfig wlan0
adb shell cat /etc/resolv.conf
adb shell cat /etc/docker/daemon.json
adb shell docker ps
adb shell docker logs edgeAgent
adb shell docker logs edgeHub

**Comment by ckcampbell248** [comment] 2019-10-07 20:55
So here's the thing...

I had tried and failed multiple times...at least 10 times...with the same results. Last night after I posted, I decided to try it once more. My device seemed to have locked up so I pressed the recessed reset button on the side (something I've done before) and it restarted but this time, it was blinking three red lights instead of three amber lights indicating that it was in it's initial setup state. I ran through the setup experience and it worked!

Today, I tried again and this time, when I went to the setup page, I was presented with the choice to only change wifi rather than reset the whole device and this worked as well!

Since I did all this at home, I plan on setting it up once more to put it on my office network on Wednesday this week. I will report back on the outcome.

**Comment by patgarr** [comment] 2019-10-07 21:06
@ckcampbell248 Office networks often block non-internal DNS requests (or require you to use an internal DNS) so at the office network if you are using 1.1.1.1/8.8.8.8 it may be blocked.

**Comment by ckcampbell248** [comment] 2019-10-09 19:40
So I'm working again but I'm at a loss to explain why. I was able to reconfigure the wifi on my dev kit again today with no issues. 

I did a "docker ps" on the device and I can see that the containers were created 3 days ago which is when the apparent reset occurred.
